gfcli:
  gen:
    dao:
    - link:     "pgsql:postgres:123456@tcp(127.0.0.1:10100)/fcm"
      group: fcm
      tables:   "fcm_token,push_err,fcm_offline_msg"
      jsonCase: "CamelLower"
    - link:     "pgsql:postgres:123456@tcp(127.0.0.1:10100)/sync_chain"
      group: sync_chain
      tables:   "chain_transfer"
      jsonCase: "CamelLower"
    - link:     "pgsql:postgres:123456@tcp(127.0.0.1:10100)/enhanced_riskctrl"
      group: "enhanced_riskctrl"
      tables:   "chain_tx"
      jsonCase: "CamelLower"
    - link:     "pgsql:postgres:123456@tcp(127.0.0.1:10100)/mpc"
      group: "mpc"
      tables:   "mpc_context"
      jsonCase: "CamelLower"
    - link:     "mysql:riskcontrol:123456@tcp(127.0.0.1:3306)/riskcontrol"
      group: "riskcontrol"
      tables:   "contractrule,contractabi,riskcontrol_rule,chaincfg"
      jsonCase: "CamelLower"
      typeMapping:
        decimal:
          type:   decimal.Decimal
          import: github.com/shopspring/decimal
        numeric:
          type:   decimal.Decimal
          import: github.com/shopspring/decimal
    - link:     "pgsql:postgres:123456@tcp(127.0.0.1:10100)/tfa"
      group: "tfa"
      tables:   "tfa"
      jsonCase: "CamelLower"