gfcli:
  gen:
    dao:
    - link:     "pgsql:postgres:123456@tcp(127.0.0.1:10100)/syncChain"
      tables:   "chain_data"
      jsonCase: "CamelLower"
    - link:     "pgsql:postgres:123456@tcp(127.0.0.1:10100)/data-riskctrl"
      tables:   "chain_data, aggNft, aggFt"
      jsonCase: "CamelLower"