// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalAdminRelayerAppDao is internal type for wrapping internal DAO implements.
type internalAdminRelayerAppDao = *internal.AdminRelayerAppDao

// adminRelayerAppDao is the data access object for table relayer_app.
// You can define custom methods on it to extend its functionality as you wish.
type adminRelayerAppDao struct {
	internalAdminRelayerAppDao
}

var (
	// AdminRelayerApp is globally public accessible object for table relayer_app operations.
	AdminRelayerApp = adminRelayerAppDao{
		internal.NewAdminRelayerAppDao(),
	}
)

// Fill with you ideas below.
