// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalAggNftDao is internal type for wrapping internal DAO implements.
type internalAggNftDao = *internal.AggNftDao

// aggNftDao is the data access object for table aggNft.
// You can define custom methods on it to extend its functionality as you wish.
type aggNftDao struct {
	internalAggNftDao
}

var (
	// AggNft is globally public accessible object for table aggNft operations.
	AggNft = aggNftDao{
		internal.NewAggNftDao(),
	}
)

// Fill with you ideas below.
