// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalAggFtDao is internal type for wrapping internal DAO implements.
type internalAggFtDao = *internal.AggFtDao

// aggFtDao is the data access object for table aggFt.
// You can define custom methods on it to extend its functionality as you wish.
type aggFtDao struct {
	internalAggFtDao
}

var (
	// AggFt is globally public accessible object for table aggFt operations.
	AggFt = aggFtDao{
		internal.NewAggFtDao(),
	}
)

// Fill with you ideas below.
