// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalChainTransferDao is internal type for wrapping internal DAO implements.
type internalChainTransferDao = *internal.ChainTransferDao

// chainTransferDao is the data access object for table chain_transfer.
// You can define custom methods on it to extend its functionality as you wish.
type chainTransferDao struct {
	internalChainTransferDao
}

var (
	// ChainTransfer is globally public accessible object for table chain_transfer operations.
	ChainTransfer = chainTransferDao{
		internal.NewChainTransferDao(),
	}
)

// Fill with you ideas below.
