// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalFcmTokenDao is internal type for wrapping internal DAO implements.
type internalFcmTokenDao = *internal.FcmTokenDao

// fcmTokenDao is the data access object for table fcm_token.
// You can define custom methods on it to extend its functionality as you wish.
type fcmTokenDao struct {
	internalFcmTokenDao
}

var (
	// FcmToken is globally public accessible object for table fcm_token operations.
	FcmToken = fcmTokenDao{
		internal.NewFcmTokenDao(),
	}
)

// Fill with you ideas below.
