// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalNftHoldingDao is internal type for wrapping internal DAO implements.
type internalNftHoldingDao = *internal.NftHoldingDao

// nftHoldingDao is the data access object for table nft_holding.
// You can define custom methods on it to extend its functionality as you wish.
type nftHoldingDao struct {
	internalNftHoldingDao
}

var (
	// NftHolding is globally public accessible object for table nft_holding operations.
	NftHolding = nftHoldingDao{
		internal.NewNftHoldingDao(),
	}
)

// Fill with you ideas below.
