// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalPushErrDao is internal type for wrapping internal DAO implements.
type internalPushErrDao = *internal.PushErrDao

// pushErrDao is the data access object for table push_err.
// You can define custom methods on it to extend its functionality as you wish.
type pushErrDao struct {
	internalPushErrDao
}

var (
	// PushErr is globally public accessible object for table push_err operations.
	PushErr = pushErrDao{
		internal.NewPushErrDao(),
	}
)

// Fill with you ideas below.
