// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalRelayerdminRelayerFeeDao is internal type for wrapping internal DAO implements.
type internalRelayerdminRelayerFeeDao = *internal.RelayerdminRelayerFeeDao

// relayerdminRelayerFeeDao is the data access object for table relayer_fee.
// You can define custom methods on it to extend its functionality as you wish.
type relayerdminRelayerFeeDao struct {
	internalRelayerdminRelayerFeeDao
}

var (
	// RelayerdminRelayerFee is globally public accessible object for table relayer_fee operations.
	RelayerdminRelayerFee = relayerdminRelayerFeeDao{
		internal.NewRelayerdminRelayerFeeDao(),
	}
)

// Fill with you ideas below.
