// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalRelayerFeeDao is internal type for wrapping internal DAO implements.
type internalRelayerFeeDao = *internal.RelayerFeeDao

// relayerFeeDao is the data access object for table relayer_fee.
// You can define custom methods on it to extend its functionality as you wish.
type relayerFeeDao struct {
	internalRelayerFeeDao
}

var (
	// RelayerFee is globally public accessible object for table relayer_fee operations.
	RelayerFee = relayerFeeDao{
		internal.NewRelayerFeeDao(),
	}
)

// Fill with you ideas below.
