// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalRelayerAppFeeDao is internal type for wrapping internal DAO implements.
type internalRelayerAppFeeDao = *internal.RelayerAppFeeDao

// relayerAppFeeDao is the data access object for table app_fee.
// You can define custom methods on it to extend its functionality as you wish.
type relayerAppFeeDao struct {
	internalRelayerAppFeeDao
}

var (
	// RelayerAppFee is globally public accessible object for table app_fee operations.
	RelayerAppFee = relayerAppFeeDao{
		internal.NewRelayerAppFeeDao(),
	}
)

// Fill with you ideas below.
