// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalRelayerTransactionsDao is internal type for wrapping internal DAO implements.
type internalRelayerTransactionsDao = *internal.RelayerTransactionsDao

// relayerTransactionsDao is the data access object for table relayer_transactions.
// You can define custom methods on it to extend its functionality as you wish.
type relayerTransactionsDao struct {
	internalRelayerTransactionsDao
}

var (
	// RelayerTransactions is globally public accessible object for table relayer_transactions operations.
	RelayerTransactions = relayerTransactionsDao{
		internal.NewRelayerTransactionsDao(),
	}
)

// Fill with you ideas below.
