// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalRelayerChannelDao is internal type for wrapping internal DAO implements.
type internalRelayerChannelDao = *internal.RelayerChannelDao

// relayerChannelDao is the data access object for table relayer_channel.
// You can define custom methods on it to extend its functionality as you wish.
type relayerChannelDao struct {
	internalRelayerChannelDao
}

var (
	// RelayerChannel is globally public accessible object for table relayer_channel operations.
	RelayerChannel = relayerChannelDao{
		internal.NewRelayerChannelDao(),
	}
)

// Fill with you ideas below.
