// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalRiskadminContractabiDao is internal type for wrapping internal DAO implements.
type internalRiskadminContractabiDao = *internal.RiskadminContractabiDao

// riskadminContractabiDao is the data access object for table contractabi.
// You can define custom methods on it to extend its functionality as you wish.
type riskadminContractabiDao struct {
	internalRiskadminContractabiDao
}

var (
	// RiskadminContractabi is globally public accessible object for table contractabi operations.
	RiskadminContractabi = riskadminContractabiDao{
		internal.NewRiskadminContractabiDao(),
	}
)

// Fill with you ideas below.
