// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalRiskadminRiskcontrolRuleDao is internal type for wrapping internal DAO implements.
type internalRiskadminRiskcontrolRuleDao = *internal.RiskadminRiskcontrolRuleDao

// riskadminRiskcontrolRuleDao is the data access object for table riskcontrol_rule.
// You can define custom methods on it to extend its functionality as you wish.
type riskadminRiskcontrolRuleDao struct {
	internalRiskadminRiskcontrolRuleDao
}

var (
	// RiskadminRiskcontrolRule is globally public accessible object for table riskcontrol_rule operations.
	RiskadminRiskcontrolRule = riskadminRiskcontrolRuleDao{
		internal.NewRiskadminRiskcontrolRuleDao(),
	}
)

// Fill with you ideas below.
