// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalRiskcontrolRuleDao is internal type for wrapping internal DAO implements.
type internalRiskcontrolRuleDao = *internal.RiskcontrolRuleDao

// riskcontrolRuleDao is the data access object for table riskcontrol_rule.
// You can define custom methods on it to extend its functionality as you wish.
type riskcontrolRuleDao struct {
	internalRiskcontrolRuleDao
}

var (
	// RiskcontrolRule is globally public accessible object for table riskcontrol_rule operations.
	RiskcontrolRule = riskcontrolRuleDao{
		internal.NewRiskcontrolRuleDao(),
	}
)

// Fill with you ideas below.
