// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalRiskadminChaincfgDao is internal type for wrapping internal DAO implements.
type internalRiskadminChaincfgDao = *internal.RiskadminChaincfgDao

// riskadminChaincfgDao is the data access object for table chaincfg.
// You can define custom methods on it to extend its functionality as you wish.
type riskadminChaincfgDao struct {
	internalRiskadminChaincfgDao
}

var (
	// RiskadminChaincfg is globally public accessible object for table chaincfg operations.
	RiskadminChaincfg = riskadminChaincfgDao{
		internal.NewRiskadminChaincfgDao(),
	}
)

// Fill with you ideas below.
