// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalSyncchainStateDao is internal type for wrapping internal DAO implements.
type internalSyncchainStateDao = *internal.SyncchainStateDao

// syncchainStateDao is the data access object for table state.
// You can define custom methods on it to extend its functionality as you wish.
type syncchainStateDao struct {
	internalSyncchainStateDao
}

var (
	// SyncchainState is globally public accessible object for table state operations.
	SyncchainState = syncchainStateDao{
		internal.NewSyncchainStateDao(),
	}
)

// Fill with you ideas below.
