// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalSyncchainChainTransferDao is internal type for wrapping internal DAO implements.
type internalSyncchainChainTransferDao = *internal.SyncchainChainTransferDao

// syncchainChainTransferDao is the data access object for table chain_transfer.
// You can define custom methods on it to extend its functionality as you wish.
type syncchainChainTransferDao struct {
	internalSyncchainChainTransferDao
}

var (
	// SyncchainChainTransfer is globally public accessible object for table chain_transfer operations.
	SyncchainChainTransfer = syncchainChainTransferDao{
		internal.NewSyncchainChainTransferDao(),
	}
)

// Fill with you ideas below.
