// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mpcsdk/mpcCommon/mpcdao/dao/internal"
)

// internalWalletAddrDao is internal type for wrapping internal DAO implements.
type internalWalletAddrDao = *internal.WalletAddrDao

// walletAddrDao is the data access object for table wallet_addr.
// You can define custom methods on it to extend its functionality as you wish.
type walletAddrDao struct {
	internalWalletAddrDao
}

var (
	// WalletAddr is globally public accessible object for table wallet_addr operations.
	WalletAddr = walletAddrDao{
		internal.NewWalletAddrDao(),
	}
)

// Fill with you ideas below.
